site_name: ProteoForge
site_description: Differential proteoform discovery for bottom-up proteomics
site_url: https://github.com/eneskemalergin/ProteoForge
repo_url: https://github.com/eneskemalergin/ProteoForge
repo_name: eneskemalergin/ProteoForge

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Configuration: config.md
  - Input and output: io.md
  - Prepare: prepare.md
  - Normalization: normalization.md
  - PreparedDataset: prepared-dataset.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true

docs_dir: docs
site_dir: site
strict: true
